config/routes.rb
Rails.application.routes.draw do
  mount Avo::Engine, at: Avo.configuration.root_path
  mount OasRails::Engine => "/docs"
  resource :session
  resources :passwords, param: :token
  resource :registrations, only: [ :new, :create ]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  resource :registrations, only: [ :new, :create ]

  namespace :public, path: "/" do
    get "home", to: "home#index"
    get "blog", to: "posts#index", as: :posts
    get "blog/:id", to: "posts#show", as: :post
    resources :markets, only: [ :index, :show ]
    resources :companies, only: [ :index, :show ]
    resources :domains, only: [ :index, :show ]
    resources :domain_emails, only: [ :index, :create ]
    root "landing_page#index"
  end

  namespace :admin do
    resources :feature_extraction_queries
    root "feature_extraction_queries#index"
  end

  namespace :app, path: "/app" do
    resources :users, only: [ :show ]
    get "dashboard", to: "dashboard#index"
    root "dashboard#index"
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get "home/index"
      get "serp", to: "serp#index"
      get "domain_emails", to: "domain_emails#index"
      get "company_domain", to: "company_domain#index"
      post "scrap_web_page", to: "scrap_web_page#create"
      post "scrap_web_pages", to: "scrap_web_pages#create"
      post "scrap_domain", to: "scrap_domain#create"
      get "hf_models", to: "hf_models#index"
      post "hf_inference", to: "hf_inference#create"
      post "analyze_web_page", to: "analyze_web_page#create"
      post "analyze_serp", to: "analyze_serp#create"
    end
  end

  # Defines the root path route ("/")
  root "public/home#index"
end

app/models/feature_extraction_query.rb
class FeatureExtractionQuery < ApplicationRecord
  include Embeddable
  validates :search_field, presence: true, uniqueness: true
end

app/controllers/admin/feature_extraction_queries_controller.rb
module Admin
  class FeatureExtractionQueriesController < ApplicationController
    before_action :set_feature_extraction_query, only: %i[ show edit update destroy ]

    # GET /feature_extraction_queries or /feature_extraction_queries.json
    def index
      @feature_extraction_queries = FeatureExtractionQuery.all
    end

    # GET /feature_extraction_queries/1 or /feature_extraction_queries/1.json
    def show
    end

    # GET /feature_extraction_queries/new
    def new
      @feature_extraction_query = FeatureExtractionQuery.new
    end

    # GET /feature_extraction_queries/1/edit
    def edit
    end

    # POST /feature_extraction_queries or /feature_extraction_queries.json
    def create
      @feature_extraction_query = FeatureExtractionQuery.new(feature_extraction_query_params)

      respond_to do |format|
        if @feature_extraction_query.save
          format.html { redirect_to [ :admin, @feature_extraction_query ], notice: "Feature extraction query was successfully created." }
          format.json { render :show, status: :created, location: @feature_extraction_query }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @feature_extraction_query.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /feature_extraction_queries/1 or /feature_extraction_queries/1.json
    def update
      respond_to do |format|
        if @feature_extraction_query.update(feature_extraction_query_params)
          format.html { redirect_to [ :admin, @feature_extraction_query ], notice: "Feature extraction query was successfully updated." }
          format.json { render :show, status: :ok, location: @feature_extraction_query }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @feature_extraction_query.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /feature_extraction_queries/1 or /feature_extraction_queries/1.json
    def destroy
      @feature_extraction_query.destroy!

      respond_to do |format|
        format.html { redirect_to admin_feature_extraction_queries_path, status: :see_other, notice: "Feature extraction query was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_feature_extraction_query
        @feature_extraction_query = FeatureExtractionQuery.find(params.expect(:id))
      end

      # Only allow a list of trusted parameters through.
      def feature_extraction_query_params
        params.expect(feature_extraction_query: [ :content, :embedding, :search_field ])
      end
  end
end

app/controllers/avo/feature_extraction_queries_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/3.0/controllers.html
class Avo::FeatureExtractionQueriesController < Avo::ResourcesController
end

app/helpers/feature_extraction_queries_helper.rb
module FeatureExtractionQueriesHelper
end

app/views/admin/feature_extraction_queries/_feature_extraction_query.html.erb
<div id="<%= dom_id feature_extraction_query %>">
  <p>
    <strong>Content:</strong>
    <%= feature_extraction_query.content %>
  </p>

  <p>
    <strong>Embedding:</strong>
    <%= feature_extraction_query.embedding %>
  </p>

  <p>
    <strong>Search field:</strong>
    <%= feature_extraction_query.search_field %>
  </p>

</div>

app/views/admin/feature_extraction_queries/_form.html.erb
<%= form_with(model: [:admin, feature_extraction_query]) do |form| %>
  <% if feature_extraction_query.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(feature_extraction_query.errors.count, "error") %> prohibited this feature_extraction_query from being saved:</h2>

      <ul>
        <% feature_extraction_query.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.textarea :content %>
  </div>

  <div>
    <%= form.label :search_field, style: "display: block" %>
    <%= form.text_field :search_field %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/feature_extraction_queries/edit.html.erb
<% content_for :title, "Editing feature extraction query" %>

<h1>Editing feature extraction query</h1>

<%= render "form", feature_extraction_query: @feature_extraction_query %>

<br>

<div>
  <%= link_to "Show this feature extraction query", [:admin, @feature_extraction_query] %> |
  <%= link_to "Back to feature extraction queries", admin_feature_extraction_queries_path %>
</div>

app/views/admin/feature_extraction_queries/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Feature extraction queries" %>

<h1>Feature extraction queries</h1>

<div id="feature_extraction_queries">
  <% @feature_extraction_queries.each do |feature_extraction_query| %>
    <%= render feature_extraction_query %>
    <p>
      <%= link_to "Show this feature extraction query", admin_feature_extraction_query_path(feature_extraction_query) %>
    </p>
  <% end %>
</div>

<%= link_to "New feature extraction query", new_admin_feature_extraction_query_path %>

app/views/admin/feature_extraction_queries/new.html.erb
<% content_for :title, "New feature extraction query" %>

<h1>New feature extraction query</h1>

<%= render "form", feature_extraction_query: @feature_extraction_query %>

<br>

<div>
  <%= link_to "Back to feature extraction queries", admin_feature_extraction_queries_path %>
</div>

app/views/admin/feature_extraction_queries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @feature_extraction_query %>

<div>
  <%= link_to "Edit this feature extraction query", edit_admin_feature_extraction_query_path(@feature_extraction_query) %> |
  <%= link_to "Back to feature extraction queries", admin_feature_extraction_queries_path %>

  <%= button_to "Destroy this feature extraction query", [:admin, @feature_extraction_query], method: :delete %>
</div>